markdown: kramdown
highlighter: rouge
title: Will Pearson
author:
  name: Will Pearson
  email: w.j.b.pearson@bath.ac.uk
  twitter: pearswj
  github: pearswj
permalink: /blog/:title.html
include: ["_lib"]
