# using mrcaron/jekyll for redcarpet 2 compatability
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "with_toc_data", "superscript"]
pygments: true
title: Will Pearson
author:
  name: Will Pearson
  email: w.j.b.pearson@bath.ac.uk
  twitter: pearswj
  github: pearswj
