markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "with_toc_data", "superscript", "smart"]
pygments: true
title: Will Pearson
author:
  name: Will Pearson
  email: w.j.b.pearson@bath.ac.uk
  twitter: pearswj
  github: pearswj
permalink: /blog/:title.html
